### PR TITLE
issue-128 adding step / static pages

### PR DESCRIPTION
**Pull request by ajcrites**
Completes issue #128  .

Changes in this pull request:

- Add Steps component and template for static pages
- Updated router to default to first step and properly link to permit locator (step 9)

### CODE REVIEW

**Comment by gotoplanb** [comment]
@ajcrites Functionally sweet. There is a side-effect of the Permit Locator header styles. Figure we'll make a separate issue to fix that, but I wanted to confirm that new-issue tactic with you versus fixing in this same branch.

screen shot 2017-03-08 at 7 44 33 pm

**Comment by ajcrites** [comment]
@gotoplanb thanks! I just slapped this together since we don't have any designs for it yet. Bjorn was talking about doing some cleanup so it doesn't look awful / creating the links etc. He can close this or maybe just piggyback on it.

**Comment by Bjorn248** [comment]
@gotoplanb fixed in this branch

**Comment by Bjorn248** [comment]
Added a bunch of `<br>` tags to make it a bit more readable. Also added `target="_blank"` to all the `a` tags so they open in new tabs, and made all the URLs `a` tags.

**Pull request merged**
