### PR TITLE
issue-39-40-41 export assets for header, body, footer

### PR DESCRIPTION
**Pull request by hollymariegibbs**
Completes issues #39 #40 #41.

Changes in this pull request:

- Created an 'images' folder
- Added sliced images for header
- Added sliced images for body
- Added sliced images for footer

### CODE REVIEW

**Comment by Bjorn248** [comment]
We will create an S3 bucket to store these assets during our next session. #51 addresses account creation. The assets will be stored in the feature branch for now until we have them on S3 and a standard way of adding them.

**Comment by gotoplanb** [comment]
@Bjorn248 For initial launch, we can even just use GitHub Pages, so we won't need to deal with AWS at all. For argument sake, let's assume we launch on GitHub Pages. How then do you recommend we store images?

**Comment by Bjorn248** [comment]
We'll have to see what the standard methods are for other sites that use github pages. I'd really like to promote AWS here though because it's cheap, simple, and most likely what we'll be running in production. No matter which hosting solution we go with I'd like to utilize travis to build to it whenever we merge into develop/master. I'll make an issue for that now.

Also, we'll likely be using Lambda for our data caching layer tracked by #53 (what @ajcrites will probably be working on soon) so we'll be using AWS one way or another.

@ajcrites originally recommended S3 for this and I agreed. I've just seen what can happen when years of binary data adds up in a repo. You end up with repos that are hundreds of MB large and old files you can never get rid of.

**Comment by Bjorn248** [comment]
I'll merge this for now. If we ever decide to not include binary data in the repo we'll have to rewrite history to get rid of it, but for now we've accepted committing images to git.

**Pull request merged**
