### PR TITLE
issue-39-40-41 assets

### PR DESCRIPTION
**Pull request by hollymariegibbs**
issue-39-40-41 assets

I made some assets for the things

### CODE REVIEW

**Comment by Bjorn248** [comment]
Hmm...is there any way to avoid having static assets committed to the repo? I'd like them somewhere else if we can avoid it. Maybe something like S3 or dropbox links? What are your thoughts? What do you normally do?

**Comment by hollymariegibbs** [comment]
There should be an images folder within the project directory that holds them, don't you agree? You mean externally link to stuff in Dropbox? I'm using my personal account to host c4gnv stuff and I don't like the idea of creating places where links can break.

**Comment by Bjorn248** [comment]
I agree I don't want links to break. I want to think about this more before merging.

**Comment by hollymariegibbs** [comment]
Relative linking is always going to be safer, and we have the storage capacity for the images.

Now, should the dev team choose to use linked icons instead of static ones (which I would also prefer), they don't have to use the ones in the images folder and we can remove them once everything is implemented.

I just wanted to make sure they're there and available so nobody _has_ to make things from scratch or be blocked by missing assets. Please go ahead and merge so they're available to use and we can go through and clean up the folder (there aren't many assets in it to begin with) once they've been implemented.

**Pull request closed without merging**
