### PR TITLE
issue-123 display count

### PR DESCRIPTION
**Pull request by Bjorn248**
Also make search case-insensitive

Completes issue #123  .

Changes in this pull request:

- Displays count of permits for that business type
- Makes search case-insensitive (e.g. brew and Brew return brewery)

### CODE REVIEW

**Comment by firoze** [comment]
@Bjorn248 good call about calling `.toLowerCase()` on the search query value as well. I have to update my pull request with this, too

**Comment by firoze** [comment]
to fix the build error, change `val` in line 61 of `businessType-list.component.ts` to ``(val: string)``

**Comment by Bjorn248** [comment]
Hmm, I'll try to get rid of all the build errors before pushing a new commit. For some reason I didn't even see them

**Comment by Bjorn248** [comment]
Adding screenshots just because

screenshot 2017-02-23 14 35 27

and

screenshot 2017-02-23 14 35 34

**Pull request merged**
