### PR TITLE
issue-113 removing business category

### PR DESCRIPTION
**Pull request by Bjorn248**
Completes issue #113

Changes in this pull request:

- Removing the notion of a "Category". We think it's arbitrary and confusing.

### CODE REVIEW

**Comment by firoze** [comment]
👌 :shipit:

**Comment by Bjorn248** [comment]
Search still works :D

**Comment by ajcrites** [comment]
@Bjorn248 please update the pull request title to match standards

**Comment by gotoplanb** [comment]
Functionally works as expected for me :shipit:

**Comment by Bjorn248** [comment]
@gotoplanb Andrew rebased. We should be ready to merge ^.^

**Pull request merged**
