### PR TITLE
upgrade to stable angular; upgrade to typescript 2; move to npm-based…

### PR DESCRIPTION
**Pull request by ghost**
Completes issue #43.

Changes in this pull request:

- upgrade to stable angular
- upgrade to typescript 2
- move to npm-based typings

### CODE REVIEW

**Comment by Bjorn248** [comment]
Nice clean up!

**Comment by Bjorn248** [comment]
Please use the guidelines for commits and feature branch naming in CONTRIBUTING.md next time

**Comment by ghost** [comment]
Touché!

**Comment by Bjorn248** [comment]
Haha, I've decided to start becoming the person that everyone hates by not merging PRs until they meet the naming conventions. Someone has to do it.

**Comment by ajcrites** [comment]
@alienlike npm-based typings means installing `@types/<library>`? For example if we wanted to use lodash or moment we could install these?

**Comment by ghost** [comment]
@ajcrites That's correct. See https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/.

**Pull request merged**
