### PR TITLE
- Angular2 templating on Business list component HTML

### PR DESCRIPTION
**Pull request by ragafoo**
Completes issue #37 + #61 

Changes in this pull request:
- Business list component extended to support templating
	-Next Step (State management and expand animation)
- HTML Angular2 templating on Body Component
- CSS Styling

### CODE REVIEW

**Comment by Bjorn248** [comment]
@ragafoo changes look good! It seems that you destroyed the changes implemented by @ajcrites to get category collapse working though. Refer to #86 for that functionality. Also, please include the issue # in the commit message. Once you resolve that this will be ready to merge!

See [https://github.com/c4gnv/business-web/blob/develop/CONTRIBUTING.md#commit-messages](https://github.com/c4gnv/business-web/blob/develop/CONTRIBUTING.md#commit-messages) for the commit message naming convention.

**Comment by ajcrites** [comment]
@ragafoo please also include a screenshot or gif demonstrating new functionality.

**Comment by ragafoo** [comment]
Sorry about wiping out your collapse animation Andrew, i'll surely use it, I'll look at reimplementing it later along with some form of state management. Go ahead and cancel the PR if you want I won't be able to work on this more for a little while.
https://goo.gl/photos/BJMxtWMWJiQ4xfxA8

**Comment by Bjorn248** [comment]
I do want to get your changes in eventually. I'll leave this open for now, maybe @ajcrites and I can cherry pick your changes so they don't remove functionality he added.

**Pull request closed without merging**
